name: Docker Image CI

on:
  push:
    branches: [ "docker-image" ]
  pull_request:
    branches: [ "docker-image" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Build and push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
          image: omkuchekar/githubtest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
